"""Async-capable Alembic environment.

Reads DATABASE_URL from the environment (falling back to app.core.config
Settings, which itself reads .env) rather than from alembic.ini, so the same
connection string is used by the app and by migrations.
"""
import asyncio
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Make `app` importable when alembic is invoked from the `ai/` directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import get_settings  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No SQLAlchemy models/metadata are autogenerated from in this skeleton --
# migrations are hand-written (see alembic/versions/*.py). Autogenerate
# support can be wired up later by pointing target_metadata at a shared
# declarative Base once ORM models exist.
target_metadata = None


def get_url() -> str:
    settings = get_settings()
    return os.environ.get("DATABASE_URL", settings.DATABASE_URL)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emits SQL, no DB connection)."""
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table_schema="runtime",
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # ai_app has no CREATE on schema `public` (Postgres 15+ revokes that by
        # default) — the version table belongs in `runtime` like everything else
        # ai_app owns (PRD §8.1), not `public`.
        version_table_schema="runtime",
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode using an async engine."""
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
